import JSZip from "jszip";

/**
 * Utility to export generated React components as a complete Next.js + Tailwind codebase.
 * Uses JSZip to compile files client-side and triggers a native browser file download.
 */
export const exportProject = {
  /**
   * Compiles the generated React code block into a complete Next.js App Router structure and triggers a ZIP download.
   * @param projectId The unique project identifier
   * @param generatedCode The raw source code of the generated page or component
   * @param projectTitle The title of the project to name the zip file
   * @returns A promise resolving to a boolean indicating export success
   */
  downloadAsZip: async (
    projectId: string,
    generatedCode: string,
    projectTitle: string
  ): Promise<boolean> => {
    try {
      const zip = new JSZip();

      // 1. package.json configuration
      const packageJson = {
        name: projectId,
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
          lint: "next lint",
        },
        dependencies: {
          react: "^19.0.0",
          "react-dom": "^19.0.0",
          next: "15.1.0",
          "lucide-react": "^0.468.0",
          clsx: "^2.1.1",
          "tailwind-merge": "^2.5.5",
          "class-variance-authority": "^0.7.1",
        },
        devDependencies: {
          typescript: "^5.0.0",
          "@types/node": "^20.0.0",
          "@types/react": "^19.0.0",
          "@types/react-dom": "^19.0.0",
          postcss: "^8.4.0",
          tailwindcss: "^3.4.0",
        },
      };

      // 2. tsconfig.json configuration
      const tsconfigJson = {
        compilerOptions: {
          target: "es5",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "node",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [
            {
              name: "next",
            },
          ],
          paths: {
            "@/*": ["./*"],
          },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"],
      };

      // 3. tailwind.config.js configuration
      const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
`;

      // 4. postcss.config.js configuration
      const postcssConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

      // 5. next-env.d.ts boilerplate
      const nextEnvD = `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information
`;

      // 6. Global CSS imports
      const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;

      // 7. Root layout configuration
      const layoutCode = `import React from "react";
import "./globals.css";

export const metadata = {
  title: "${projectTitle} - Generated by Novastack.ai",
  description: "Production-ready frontend designed dynamically.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="h-full antialiased">
      <body class="min-h-full flex flex-col bg-slate-50 text-slate-900">
        {children}
      </body>
    </html>
  );
}
`;

      // 8. Add all config files to ZIP root
      zip.file("package.json", JSON.stringify(packageJson, null, 2));
      zip.file("tsconfig.json", JSON.stringify(tsconfigJson, null, 2));
      zip.file("tailwind.config.js", tailwindConfig);
      zip.file("postcss.config.js", postcssConfig);
      zip.file("next-env.d.ts", nextEnvD);

      // 9. Add app files
      const appFolder = zip.folder("app");
      if (appFolder) {
        appFolder.file("globals.css", globalsCss);
        appFolder.file("layout.tsx", layoutCode);
        appFolder.file("page.tsx", generatedCode);
      }

      // 10. Generate ZIP blob client-side
      const blob = await zip.generateAsync({ type: "blob" });

      // 11. Trigger dynamic native browser download
      const downloadLink = document.createElement("a");
      const cleanFileName = projectTitle.replace(/[^a-z0-9]/gi, "_").toLowerCase();
      downloadLink.href = URL.createObjectURL(blob);
      downloadLink.download = `${cleanFileName}_nextjs_export.zip`;
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);

      return true;
    } catch (err) {
      console.error("ZIP Export failed:", err);
      return false;
    }
  },
};
